name: qpay
description: Qpay payment app


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.11+15
version: 1.0.13+3
environment:
  #sdk: ">=2.12.0 <3.0.0"
   sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flustars: ^2.0.1
  intl: ^0.20.2
  dio: ^5.3.3
  rxdart: ^0.27.7
  common_utils: ^2.1.0
  url_launcher: ^6.1.14
  fluro: ^2.0.5
  cupertino_icons: ^1.0.6
  sprintf: ^7.0.0
  cached_network_image: ^3.3.0
  keyboard_actions: ^4.2.0
  oktoast: ^3.3.2
  provider: ^6.0.5
  step_progress_indicator: ^1.0.2
  device_info_plus: ^9.0.3
  local_auth: ^2.1.7
  flutter_native_contact_picker: ^0.0.4
  another_flushbar: ^1.12.30
  dotted_border: ^2.0.0+3
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  path: ^1.8.3
  group_button: ^5.3.3
  #qr_code_scanner: ^1.0.1
  event_bus: ^2.0.0
  cron: ^0.5.1
  #screenshot: ^2.1.0
  animated_splash_screen: ^1.3.0
  collection: ^1.18.0
  toggle_switch: ^2.1.0
  flutter_phone_direct_caller: ^2.1.1
  #contacts_service: ^0.6.3
  permission_handler: ^11.0.0
  pinput: ^3.0.1
  timer_count_down: ^2.2.0
  connectivity_plus: ^4.0.2
  get_it: ^7.6.4
#  flutter_local_notifications: ^14.1.1
  overlay_support: ^2.1.0
  #flutter_app_badger: ^1.5.0
  flutter_cupertino_datetime_picker: ^3.0.0
  #image_gallery_saver: ^2.0.3
  expandable: ^5.0.1
  image_picker: ^1.0.4
 # open_mail_app: ^0.4.5
  app_settings: ^5.1.1
 # share_files_and_screenshot_widgets: ^1.0.6
  #new_version: ^0.3.1
  package_info_plus: ^4.1.0
 # image_cropper: ^5.0.0
  flutter_scrolling_fab_animated: ^0.1.4
  webview_flutter: ^4.2.4

  #advance_pdf_viewer2: any #^2.0.5+1
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_analytics: ^10.5.0
  firebase_messaging: ^14.6.9
  network_info_plus: ^4.0.2
  #google_mlkit_face_detection: ^0.8.0
  #flutter_countdown_timer: ^4.1.0

  geolocator: ^9.0.0
  #added
  mobile_scanner: ^7.0.1
  contacts_service_plus: ^0.0.2
  flutter_inappwebview: ^6.1.5
  pdfx: ^2.9.2
  share_plus: ^11.0.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  asn1lib: ^1.6.5
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^4.2.3
  image_cropper: ^9.1.0
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^30.2.7


dependency_overrides:
  #decimal: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl: ^0.17.0
  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/app_icon_san.png"
  android:  "launcher_icon"
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/dashboard/
    - assets/images/cards/
    
  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/cour.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_regular.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/sf_ui_regular.ttf
    - family: San
      fonts:
        - asset: assets/fonts/product_sans_bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica_neue.ttf
        - asset: assets/fonts/helvetica_neue_thin.ttf
        - asset: assets/fonts/helvetica_neue_light.ttf
        - asset: assets/fonts/helvetica_neue_medium.ttf
    - family: OCR
      fonts:
        - asset: assets/fonts/ocraext.TTF
    - family:  TakaIcon
      fonts:
        - asset: assets/fonts/TakaIcon.ttf
    - family: TiroBangla
      fonts:
        - asset: assets/fonts/TiroBangla-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
